### ISSUE TITLE
Upgrade repo to modern tooling

### ISSUE THREAD

**Issue by mattpocock** [supermacro/neverthrow#572]
- [ ] Upgrade TS to latest
- [ ] Upgrade to strict mode #567
- [ ] Move to vitest #571 
- [ ] Move to tsup #570 
- [ ] Add arethetypeswrong/cli #569
- [ ] Upgrade ESLint and migrate the config
- [ ] Upgrade prettier

**Comment by jessekrubin** [comment]
This may fit here w/ respect to modern-talk

Why does this library use `namespace`s (eg `result.ts`)? is it a legacy thing?
